package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

/* JADX INFO: loaded from: classes.dex */
public final class zzr<R extends Result> extends OptionalPendingResult<R> {
    private final zzb<R> zzaiy;

    public zzr(PendingResult<R> pendingResult) {
        if (!(pendingResult instanceof zzb)) {
            throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
        }
        this.zzaiy = (zzb) pendingResult;
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public R await() {
        return (R) this.zzaiy.await();
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public R await(long j, TimeUnit timeUnit) {
        return (R) this.zzaiy.await(j, timeUnit);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public void cancel() {
        this.zzaiy.cancel();
    }

    @Override // com.google.android.gms.common.api.OptionalPendingResult
    public R get() {
        if (isDone()) {
            return (R) await(0L, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public boolean isCanceled() {
        return this.zzaiy.isCanceled();
    }

    @Override // com.google.android.gms.common.api.OptionalPendingResult
    public boolean isDone() {
        return this.zzaiy.isReady();
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public void setResultCallback(ResultCallback<? super R> callback) {
        this.zzaiy.setResultCallback(callback);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public void setResultCallback(ResultCallback<? super R> callback, long time, TimeUnit units) {
        this.zzaiy.setResultCallback(callback, time, units);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public void zza(PendingResult.zza zzaVar) {
        this.zzaiy.zza(zzaVar);
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public Integer zzpa() {
        return this.zzaiy.zzpa();
    }
}
